# Enable Analog Input
CONFIG_ADC=y

# Enable Analog Input Module
CONFIG_ANALOG_INPUT=y
# CONFIG_ANALOG_INPUT_LOG_LEVEL_DBG=y
# CONFIG_ANALOG_INPUT_REPORT_INTERVAL_MIN=22


# Just in case, you don't RTFM
CONFIG_INPUT=y

# Enable ZMK mouse emulations
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_IDLE_TIMEOUT=3600000